</div>
<footer id='footer'>
<div class='container_12'>
	<div class='grid_12'>
		<div class='footer-icon align-center'>
			<a class='top' href='#top'></a>
		</div>
	</div>
</div>
</footer>
</div>
<script src='js/jquery.min.js'></script>
<script defer src='js/functions.js'></script>

<!--[if lt IE 7 ]><script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script> <script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})});</script><![endif]-->
</body>
</html>
