<nav id="nav">
<ul class="menu collapsible shadow-bottom">
	<li><a href="dashboard.html" class=current><img
			src="img/icons/packs/fugue/16x16/dashboard.png">Dashboard</a>
	</li>
	
	<li><a href="#"><img
			src="img/icons/packs/fugue/16x16/user-white.png">Contacts</a>
		<ul class="sub">
			<li><a href="list_block.html">Customers</a>
			</li>
			<li><a href="list_shortcut.html">Suppliers</a>
			</li>
			<li><a href="list_shortcut.html">Employee</a>
			</li>
		</ul></li>
	<li><a href="#"><img
			src="img/icons/packs/fugue/16x16/newspaper.png">Documents</a>
		<ul class="sub">
			<li><a href="javascript:void(0);">Invoices</a>
			</li>
			<li><a href="javascript:void(0);">Lettres</a>
			</li>
			<li><a href="javascript:void(0);">Special documents</a>
			</li>
		</ul></li>
	<li><a href="#"><img
			src="img/icons/packs/fugue/16x16/user-white.png">Application users</a>
		<ul class="sub">
			<li><a href="javascript:void(0);">List of users</a>
			</li>
			<li><a href="javascript:void(0);">Add application user</a>
			</li>
		</ul></li>
</ul>
</nav>
